### ISSUE TITLE
parsing error

### ISSUE THREAD

**Issue by AnotherWayIn** [Fist0urs/kerberom#4]
Hey,

For some reason the tool pulls out the first hash fine, but then i get the error below and it dies, any ideas?:

running latest version on Kali 64 rolling ed.
thanks

[+] Building TGS-REQ for SPN 'mssqlsvc/xxxxx:1267' and account 'xxxxbackup'... Done!
  [+] Sending TGS-REQ to xxxxxx.com... Done!
  [+] Receiving TGS-REP from xxxxxx.com... Done!
[+] Parsing TGS-REP from xxxx..com..Traceback (most recent call last):
  File "kerberom.py", line 557, in <module>
    DataSubmitted.TGS_attack()
  File "kerberom.py", line 204, in TGS_attack
    tgs_rep = parse_TGS_REP(sock, subkey, spn, samaccountname, self.DC_addr)[0]
  File "kerberom.py", line 407, in parse_TGS_REP
    tgs_rep, tgs_rep_enc = decrypt_tgs_rep(data, subkey)
  File "/root/tools/kerberos/kerberom/modules/rom/krb5.py", line 443, in decrypt_tgs_rep
    return _decrypt_rep(data, key, TgsRep(), EncTGSRepPart(), 9) # assume subkey
  File "/root/tools/kerberos/kerberom/modules/rom/krb5.py", line 430, in _decrypt_rep
    rep = decode(data, asn1Spec=spec)[0]
  File "/usr/lib/python2.7/dist-packages/pyasn1/codec/ber/decoder.py", line 825, in __call__
    stGetValueDecoder, self, substrateFun
  File "/usr/lib/python2.7/dist-packages/pyasn1/codec/ber/decoder.py", line 50, in valueDecoder
    value, _ = decodeFun(head, asn1Spec, tagSet, length)
  File "/usr/lib/python2.7/dist-packages/pyasn1/codec/ber/decoder.py", line 831, in **call**
    '%s not in asn1Spec: %s' % (tagSet, asn1Spec)
pyasn1.error.PyAsn1Error: [0:32:16]+[64:32:30] not in asn1Spec: TgsRep(componentType=NamedTypes(NamedType('pvno', Integer(tagSet=TagSet((), Tag(tagClass=0, tagFormat=0, tagId=2), Tag(tagClass=128, tagFormat=0, tagId=0)))), NamedType('msg-type', Integer(tagSet=TagSet((), Tag(tagClass=0, tag

**Comment by Fist0urs** [comment]
Hi!

Can you give me some more information please? (DC OS, length of SPN)

Thanks

**Comment by Fist0urs** [comment]
This is due to pyasn1 version

**Comment by ghost** [comment]
Then what is the good version ? Why is it not updated in setup.py ?

**Comment by Fist0urs** [comment]
I'm working on it at the moment, a new version should be working with the last pyasn1 version soon
